### ISSUE TITLE
Does you library works with zabbix 3.0?

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [hengyunabc/metrics-zabbix#2]
A command 
zabbix_sender -z zabbixHost -p 10051 -s "dev002-All-Series" -k test.ping.count -o 09
Prints
info from server: "processed: 1; failed: 0; total: 1; seconds spent: 0.017689"

But with your sender I got 
processed: 0; failed: 1; total: 1;

Does you library support interaction with zabbix 3.0?

**Comment by hengyunabc** [comment]
Try to use 

``` xml
        <dependency>
            <groupId>io.github.hengyunabc</groupId>
            <artifactId>zabbix-sender</artifactId>
            <version>0.0.3</version>
        </dependency>
```

zabbix-sender `0.0.1` do not support zabbix 3.

**Comment by C-h-e-r-r-y** [comment]
Thank you for really quick replay. WIth that dependency it works.

**Comment by hengyunabc** [comment]
`metrics-zabbix` 0.0.3 has bean push to maven central repository, which support zabbix 3.0.
